FROM golang:latest
ARG ENVIRONMENT
ARG HELLGO_API_PORT

ENV ENVIRONMENT="${ENVIRONMENT}"
ENV HELLGO_API_PORT="${HELLGO_API_PORT}"

RUN echo "ENVIRONMENT: ${ENVIRONMENT}"
RUN echo "HELLGO_API_PORT: ${HELLGO_API_PORT}"
RUN mkdir /app
ADD . /app/
WORKDIR /app
RUN ls
RUN go build -o main .
CMD ["/app/main"]