version: '2'
services:
    hellgo:
        build:
            context: .
            args:
                - ENVIRONMENT=${ENVIRONMENT}
        ports:
            - 10020:10020
        environment:
            - ENVIRONMENT=${ENVIRONMENT}
            #- HELLGO_API_PORT=${HELLGO_API_PORT}
            #- HELLGO_API_URL=${HELLGO_API_URL}
            #- HELLGO_API_USER=${HELLGO_API_USER}
            #- HELLGO_API_PASSWORD=${HELLGO_API_PASSWORD}
        #env_file: 
            #- vars.env
