FROM golang:latest
ARG ENVIRONMENT

ENV ENVIRONMENT="${ENVIRONMENT}"
ENV HELLGO_API_PORT="${HELLGO_API_PORT}"

RUN echo "ENVIRONMENT: ${ENVIRONMENT}"
RUN mkdir /app
ADD . /app/
WORKDIR /app
RUN ls
RUN go build -o main .
CMD ["/app/main"]